-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"

- id: go-lint
  name: "golint"
  entry: staticcheck ./...
  files: '\.go$'
  language: "script"
  description: "Runs `staticcheck`, requires golang"
